export const CATEGORIES_ACTION_TYPE = {
  FETCH_CATEGORIES_SUCCESS: 'categories/FETCH_CATEGORIES_SUCCESS',
  FETCH_CATEGORIES_FAILED: 'categories/FETCH_CATEGORIES_FAILED',
  FETCH_CATEGORIES_START: 'categories/FETCH_CATEGORIES_START',
};
